server:
  port: 8080
spring:
  application:
    name: pricing
  rabbitmq:
    addresses: localhost:5672
    host: host
    port: 5672
    username: myapp
    password: mypass
  jackson:
    time-zone: Europe/London

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    prices: prices.queue
  routing-keys:
    internal-notification: internal.prices.routing-key

publisher:
  configurationFile: stocks.csv
  intervalInMills: 50
  publishAsync: false

