server:
  port: 8081
spring:
  application:
    name: price-request
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  rabbitmq:
    addresses: localhost:5672
    host: host
    port: 5672
    username: myapp
    password: mypass
  jackson:
    time-zone: Europe/London

logging:
  level:
    root: INFO

