server:
  port: 8081
spring:
  application:
    name: price-request
  rabbitmq:
    addresses: localhost:5672
    host: host
    port: 5672
    username: myapp
    password: mypass

logging:
  level:
    root: DEBUG

